// <auto-generated />
using System;
using ContextoDev.TallerHexagonal.Warehouse.Infraestructura.Modelo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContextoDev.TallerHexagonal.Warehouse.Infraestructura.Modelo.Migrations
{
    [DbContext(typeof(ModeloWareHouse))]
    partial class ModeloWareHouseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ContextoDev.TallerHexagonal.Warehouse.Agregados.OrdenCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ordenCompra", (string)null);
                });

            modelBuilder.Entity("ContextoDev.TallerHexagonal.Warehouse.Agregados.OrdenCompraDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrdenCompraId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrdenCompraId1")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductoId1")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT")
                        .HasColumnName("subtotal");

                    b.HasKey("Id");

                    b.HasIndex("OrdenCompraId");

                    b.HasIndex("OrdenCompraId1");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ProductoId1");

                    b.ToTable("ordenCompraDetalle", (string)null);
                });

            modelBuilder.Entity("ContextoDev.TallerHexagonal.Warehouse.Agregados.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("ContextoDev.TallerHexagonal.Warehouse.Agregados.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("ruc");

                    b.HasKey("Id");

                    b.HasIndex("Ruc")
                        .IsUnique();

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("ContextoDev.TallerHexagonal.Warehouse.Agregados.OrdenCompraDetalle", b =>
                {
                    b.HasOne("ContextoDev.TallerHexagonal.Warehouse.Agregados.OrdenCompra", null)
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContextoDev.TallerHexagonal.Warehouse.Agregados.OrdenCompra", "OrdenCompra")
                        .WithMany()
                        .HasForeignKey("OrdenCompraId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContextoDev.TallerHexagonal.Warehouse.Agregados.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContextoDev.TallerHexagonal.Warehouse.Agregados.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenCompra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ContextoDev.TallerHexagonal.Warehouse.Agregados.Producto", b =>
                {
                    b.OwnsOne("ContextoDev.TallerHexagonal.Warehouse.ObjetosValor.Nombre", "Nombre", b1 =>
                        {
                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Nombre");

                            b1.HasKey("ProductoId");

                            b1.ToTable("productos");

                            b1.WithOwner()
                                .HasForeignKey("ProductoId");
                        });

                    b.Navigation("Nombre")
                        .IsRequired();
                });

            modelBuilder.Entity("ContextoDev.TallerHexagonal.Warehouse.Agregados.Proveedor", b =>
                {
                    b.OwnsOne("ContextoDev.TallerHexagonal.Warehouse.ObjetosValor.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("ProveedorId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CallePrincipal")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("direccion_calle_principal");

                            b1.Property<string>("CalleSecundaria")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("direccion_calle_secundaria");

                            b1.Property<string>("Ciudad")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("direccion_ciudad");

                            b1.Property<string>("Numero")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("direccion_numero");

                            b1.Property<string>("Pais")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("direccion_pais");

                            b1.HasKey("ProveedorId");

                            b1.ToTable("proveedores");

                            b1.WithOwner()
                                .HasForeignKey("ProveedorId");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("ContextoDev.TallerHexagonal.Warehouse.Agregados.OrdenCompra", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
